### ISSUE TITLE
wrong information in the app registration process

### ISSUE THREAD

**Issue by omarmallat** [microsoftgraph/dotnet-aad-query-sample#9]
you're asking users to add `http://localhost` as redirect URI, and this won't work. The default redirect uri for wpf is now `https://login.microsoftonline.com/common/oauth2/nativeclient` which is proposed by default during the app registration process on azure portal. Instead of asking users to add the localhost uri, you may tell them to select the proposed nativeclient uri only.

**Comment by Licantrop0** [comment]
Hi @omarmallat, I tried to register a new app and it looks like it is still accepting http://localhost as redirect URI:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/2388430/163494800-5cd2a64b-2621-48b2-a7e6-5f28aaca6d1d.png">

I also migrated the sample project to use Azure.Identity instead of MSAL, can you try again and see if you still get an error?

**Comment by omarmallat** [comment]
If I add localhost, and then I try to login it shows me an error saying that I the redirect uri is not matching.
Error disappear once I select the nativeclient uri.
Not sure if this is because I use .Net 6 instead of 5.
Regards

**Comment by Licantrop0** [comment]
Hi @omarmallat do you still have the issue? The main branch has been updated to .NET 7, and the WinUI branch has another project in WinUI if you are interested.

**Comment by Licantrop0** [comment]
Hi @omarmallat do you still have the issue? The main branch has been updated to .NET 7, and the WinUI branch has another project in WinUI if you are interested.
